// productos.js
const productos = [
  {
    id: 1,
    nombre: "Jabón Natural de Propóleo de Máxima Pureza",
    referencia: "VP-001",
    descripcion: "De uso cotidiano facial y corporal, este jabón polivalente es apto para todo tipo de pieles, incluso las más sensibles y delicadas. Recomendado en afecciones cutáneas. Muy recomendado también para la higiene de la zona íntima.",
    precio: 17.55,
    imagen: "/Archivos/imagenes/Productos/producto1.png",
    categoria: "Vitalidad",
    stock: 40,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 2,
    nombre: "Mousse Facial Limpiador Reconfortante",
    referencia: "VP-002",
    descripcion: "Aporta energía extra y mejora visiblemente el aspecto de tu piel. Limpia en profundidad la polución y el maquillaje. Actúa como antioxidante. Reduce enrojecimientos y mejora la psoriasis y los eccemas cutáneos.",
    precio: 21.75,
    imagen: "Archivos/imagenes/Productos/producto2.png",
    categoria: "Vitalidad",
    stock: 30,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 3,
    nombre: "Tónico Facial Calmante Libre de Alcohol",
    referencia: "VP-003",
    descripcion: "Mayor relajación, limpieza, mimo y salud a tu piel, con este tónico, especialmente indicado para pieles sensibles, secas, o equilibradas que no necesiten de base alchólica para mitigar la secreción sebácea.",
    precio: 15.90,
    imagen: "Archivos/imagenes/Productos/producto3.png",
    categoria: "Vitalidad",
    stock: 25,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 4,
    nombre: "Mascarilla Regenerativa de Multivitaminas",
    referencia: "VP-004",
    descripcion: "Mascarilla antioxidante iluminadora que trabaja  en diferentes aspectos del tratamiento cutáneo. Actúa disminuyendo los radicales libres de las células, restableciendo su ADN y remineralizando la piel.",
    precio: 36.90,
    imagen: "Archivos/imagenes/Productos/producto4.png",
    categoria: "Vitalidad",
    stock: 20,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 5,
    nombre: "Contorno de Ojos Revitalizante Intensivo",
    referencia: "VP-005",
    descripcion: "Contorno pericular que ralentiza el evejecimiento de la piel y la formación de nuevas arrugas, reduce activamente las líneas existentes, recupera la firmeza, elasticidad, suavidad y tonalidad unificada. ",
    precio: 30.10,
    imagen: "Archivos/imagenes/Productos/producto5.png",
    categoria: "Vitalidad",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 6,
    nombre: "Sérum Facial Activador Vitamina C",
    referencia: "VP-006",
    descripcion: "Recomendado para pieles maduras, con arrugas vísibles, manchas, cicratices y decoloraciones. Potencia las defensas naturales de la piel. Ideal en tratamientos antimanchas, alisadores y antienvejicimiento.",
    precio: 47.80,
    imagen: "Archivos/imagenes/Productos/producto6.png",
    categoria: "Vitalidad",
    stock: 12,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 7,
    nombre: "Crema Facial Regeneradora Calmante",
    referencia: "VP-007",
    descripcion: "Para todas las pieles, esta crema estimula la renovación celular, rehidrata, nutre y aporta firmeza. Contribuye en la reducción de arrugas, unifica y equilibra la piel, estimulando la producción de endorfinas y serotonias.Tus dosis de buen rollo.",
    precio: 68.80,
    imagen: "Archivos/imagenes/Productos/producto7.png",
    categoria: "Vitalidad",
    stock: 18,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 8,
    nombre: "Crema Facial Multicorrectora Hipoalergénica",
    referencia: "VP-008",
    descripcion: "Para todas las pieles, esta crema está formulada para reparar la salud de la piel, con activos protectores, calmantes y nutritivos. Refuerza y restaura la microbiota de la piel. Ideal para pieles sensibles, atópicas o con desequilibrios cutáneos.",
    precio: 74.50,
    imagen: "Archivos/imagenes/Productos/producto8.png",
    categoria: "Vitalidad",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 9,
    nombre: "Crema Hidratación Inmediata Acumulada",
    referencia: "VP-009",
    descripcion: "Para todas las pieles, esta crema favorece la hidratación intensa a la piel del rostro. Ideal para pieles jóvenes aventuras. Hidratación cutánea óptima durante 72 horas, de forma inmediata, con sistema de liberación secuencial. ",
    precio: 38.70,
    imagen: "Archivos/imagenes/Productos/producto9.png",
    categoria: "Vitalidad",
    stock: 20,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 10,
    nombre: "Crema Facial Reversaging Holística",
    referencia: "VP-010",
    descripcion: "Para pieles exigentes que necesitan un efecto crono-regénesis profundo. En esta joya dermoemocosmética, las patentes de última generación y la naturaleza se funden para lograr efectos rápidos y profundos en la piel.",
    precio: 68.80,
    imagen: "Archivos/imagenes/Productos/producto10.png",
    categoria: "Vitalidad",
    stock: 10,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 11,
    nombre: "Elixir Corporal Nutritivo y Energizante",
    referencia: "VP-011",
    descripcion: "Aceite corporal, vivificante para la piel y la mente con alto poder regenerativo y equilibrante. Recomendado para mantener la piel de todo el cuerpo hidratada, nutrida, sin imperfecciones y saludable. Destaca su eficacia como antioxidante y regenerador celular.",
    precio: 28.70,
    imagen: "Archivos/imagenes/Productos/producto11.png",
    categoria: "Vitalidad",
    stock: 12,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 12,
    nombre: "Catalizador Emocional del Hogar",
    referencia: "VP-012",
    descripcion: "Creado con más de una docena de esencias aromáticas y joyas de la fitoterapia, con el objetivo de que la estancia que te envuelve transmita seguridad, autoestima, amor propio y autoconfiaza. Te ayudará a catalizar tus emociones y disfrutar de un estado personal que genere belleza, autoestima y armonía a tu cuerpo y tu alma.",
    precio: 23.65,
    imagen: "Archivos/imagenes/Productos/producto12.png",
    categoria: "Vitalidad",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 13,
    nombre: "Jabón Natural de Azufre de Máxima Pureza",
    referencia: "VP-013",
    descripcion: "Especialmente indicado como regulador de las glándulas sebáceas y como normalizador de la función cutánea, gracias a lo cual, posee propiedades antiseborreicas y desinfectantes. Posee además una actividad purificante y antiséptica.",
    precio: 19.10,
    imagen: "Archivos/imagenes/Productos/producto13.png",
    categoria: "Serenidad",
    stock: 25,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 14,
    nombre: "Leche Facial Limpiadora Renovadora Alto Rendimiento",
    referencia: "VP-014",
    descripcion: "Elimina las impuerzas y el maquillaje de manera eficaz, hidratando y regenerando en profundidad. Su combinación única con niacinamida, inositol y geneciana amarilla, protege la piel y ayuda a potenciar su elasticidad, regeneración y luminosidad.",
    precio: 35.20,
    imagen: "Archivos/imagenes/Productos/producto14.png",
    categoria: "Serenidad",
    stock: 20,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 15,
    nombre: "Mascarilla Exfoliante Equilibrante Nutritiva",
    referencia: "VP-015",
    descripcion: "Para todo tipo de pieles, esta mascarilla exfoliante posee una doble acción: hidrata y nutre, mientras exfolia tu piel. Recomendada para pieles maduras, acnéicas,sensibles o las que presentan sequdad o poros dilatados.",
    precio: 34.50,
    imagen: "Archivos/imagenes/Productos/producto15.png",
    categoria: "Serenidad",
    stock: 18,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 16,
    nombre: "Tónico Facial Nutritivo Calmante",
    referencia: "VP-016",
    descripcion: "Formulario con la finalidad de penetrar en la delicada piel del contorno de ojos para descongestionar, ayudar en la microcirculación y drenar sus tejidos perioculares, aportando una aparencia más despejado, libre de tensiones y mayor salud y belleza a la mirada.",
    precio: 15.90,
    imagen: "Archivos/imagenes/Productos/producto16.png",
    categoria: "Serenidad",
    stock: 22,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 17,
    nombre: "Contorno de Ojos Drenante Descongestivo",
    referencia: "VP-017",
    descripcion: "Formulada con la finalidad de penetrar en la dedicada piel del contorno de ojos para descongestionar, ayudar en la microcirculación y drenar sus tejidos perioculares, aportando una aparencia más despejado, libre de tensiones y mayor salud y belleza a la mirada.",
    precio: 39.15,
    imagen: "Archivos/imagenes/Productos/producto17.png",
    categoria: "Serenidad",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 18,
    nombre: "Sérum Facial Protector Regenerativo",
    referencia: "VP-018",
    descripcion: "Sérum de alta prenetración con patentes naturales de última generación, que logra desintoxicar, proteger ante agresiones, externas, hidratar en profundidad y desestresa las células de la piel, aportando un importante efecto regenerante.",
    precio: 60.90,
    imagen: "Archivos/imagenes/Productos/producto18.png",
    categoria: "Serenidad",
    stock: 12,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 19,
    nombre: "Crema Facial Regeneradora Biocolágeno",
    referencia: "VP-019",
    descripcion: "Diseñado para desestresar, purificar, recobrar la vitalidad y el brillo natural. Su fórmula, rica en biocolágeno marino, vitaminas y ácidas grasos protege y equilibra la dermis, logrando cambios profundos y significativos a las pocas semanas de uso.",
    precio: 68.80,
    imagen: "Archivos/imagenes/Productos/producto19.png",
    categoria: "Serenidad",
    stock: 10,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 20,
    nombre: "Crema Facial Reguladora Antiacné",
    referencia: "VP-020",
    descripcion: "Novedosa formulación para equilibrar y purificar pieles mixtas y acnéicas, con un completo y sostificado remedio emocional antiestrés. Equilibria imperfecciones por desajustes hormonales, tendencias hereditarias y hábitos de higiene.",
    precio: 68.80,
    imagen: "Archivos/imagenes/Productos/producto20.png",
    categoria: "Serenidad",
    stock: 8,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 21,
    nombre: "Crema Facial Antiedad Ultra Confort",
    referencia: "VP-021",
    descripcion: "De máxima hidratación y nutrición, ideal para pieles con tendencia a la sequedad. Un perfecto aliado para luchar contra el envejecimiento prematuro, favoreciendo la calma, el sosiego, el descanso y la plenitud deseada.",
    precio: 65.85,
    imagen: "Archivos/imagenes/Productos/producto21.png",
    categoria: "Serenidad",
    stock: 10,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 22,
    nombre: "Elixir Corporal Relajante Liberador",
    referencia: "VP-022",
    descripcion: "Para todo tipo de pieles, este aceite corporal está pensado para desintoxicar, purificar, nutrir y desestresar la piel y la mente, favoreciendo el descanso, la calma interior y la liberación de las tensiones limitantes acumuladas.",
    precio: 32.45,
    imagen: "Archivos/imagenes/Productos/producto22.png",
    categoria: "Serenidad",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 23,
    nombre: "Catalizador Emocional del Hogar",
    referencia: "VP-023",
    descripcion: "Creado para que la estancia que te envuelve transmita relajación, calma, sosiego, favorezca el sueño reparador, nos ayude a reducir la ansiedad; y a la vez, contribuya a tener mayor control de nuestro estado emocional, en los casos en los que estamos afrontando situaciones de desapojo, o de superación de cualquier dpendencia.",
    precio: 23.65,
    imagen: "Archivos/imagenes/Productos/producto23.png",
    categoria: "Serenidad",
    stock: 12,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 24,
    nombre: "Desmaquillante Facial Bifásico Nutritivo",
    referencia: "VP-024",
    descripcion: "Recomendado para retirar el maquillaje resistente y de larga duración, eliminand en profundidad las impurezas del rostro; especialmente, en caso de pieles sensibles, maduras y muy secas. Idóneo para ojos sensibles y lentillas.",
    precio: 34.40,
    imagen: "Archivos/imagenes/Productos/producto24.png",
    categoria: "Abundancia",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 25,
    nombre: "Tónico Facial Rejuvenecedor Vivificante",
    referencia: "VP-025",
    descripcion: "Ayuda a mantener una buena función de la piel, la circulación periférica y la tonificación muscular. Posee efectos, venotónicos, actúa como un poderoso antioxidante y nutre los tejidos para equilibrar el funcionamiento celular.",
    precio: 15.90,
    imagen: "Archivos/imagenes/Productos/producto25.png",
    categoria: "Abundancia",
    stock: 20,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 26,
    nombre: "Mascarilla Facial Unificadora Reestructurante",
    referencia: "VP-026",
    descripcion: "Depura los tejidos, elimina toxinas y mejora la circulación sanguínea. Logra un efecto inmediato en la desinflamación, el drenaje facial y borra los signos de cansancio apotando un rostro claramente despejado y saludable.",
    precio: 43.40,
    imagen: "Archivos/imagenes/Productos/producto26.png",
    categoria: "Abundancia",
    stock: 15,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 27,
    nombre: "Contorno de Ojos Reparador Regenerante",
    referencia: "VP-027",
    descripcion: "Crema periocular regenerante, que refuerza las defensas naturales, neutriliza los radicales libres, que deterioran, debilitan y envejecen el rostro. Suero de tratamiento intensivo que reduce los signos de fatiga.",
    precio: 29.00,
    imagen: "Archivos/imagenes/Productos/producto27.png",
    categoria: "Abundancia",
    stock: 12,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 28,
    nombre: "Sérum Ácido Hialurónico Epidérmico",
    referencia: "VP-028",
    descripcion: "Fórmula innovadora que hidrata altamente la piel. Un día equivale a 14 tratamientos con cualquier otro ácido. La piel queda plenamente hidratada en tan sólo 4h tras su primer aplicación mostrando resultados claramente visibles.",
    precio: 49.65,
    imagen: "Archivos/imagenes/Productos/producto28.png",
    categoria: "Abundancia",
    stock: 10,
    envio: "Envío gratis a partir de 50 €",
    plazo: "Plazo de 1–3 días laborables",
  },
  {
    id: 29,
    nombre: "Crema Facial Lifting Restaudador Antiedad",
    referencia: "VP-029",
    descripcion: "<b>Premio Crema Líder del Tour de la Belleza 2023</b><br>Diamante negro, oro, platino, trufas, células Madre, hongos, vitaminas y activos que logran un poderoso efecto Lifting y Flash Natural. Elimina y mejora las líneas de expresión.",
    precio: 146.25,
    imagen: "Archivos/imagenes/Productos/producto29.png",
    categoria: "Abundancia",
    stock: 20,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 30,
    nombre: "Antiflcidez Reafirmante Óvalo Facial y Cuello",
    referencia: "VP-030",
    descripcion: "<b>Premio Sérum Líder del Tour de la Belleza 2024</b><br> Concentrado que previene y revierte la pérdida de fiemeza del rostro, óvalo facial, cuello y escote, reafirmando las zonas que presentan los signos de evejecimiento.",
    precio: 65.35,
    imagen: "Archivos/imagenes/Productos/producto30.png",
    categoria: "Abundancia",
    stock: 20,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 31,
    nombre: "Elixir Corporal Sensitivo Revigorizante",
    referencia: "VP-031",
    descripcion: "Aceite corporal que ayuda en la reparación, evita desajustes como imperfecciones, hidrata y devuelve elasticidad a la piel, nutriéndola y equilibrando su regeneración. La piel queda suave, sedosa y muy sensual.",
    precio: 40.60,
    imagen: "Archivos/imagenes/Productos/producto31.png",
    categoria: "Abundancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 32,
    nombre: "Catilizador Emocional del Hogar",
    referencia: "VP-032",
    descripcion: "Concebido para que el aura que envuelve tu hogar, transmita un culmen Mágico sobre las personas que se encuentran en la estancia, gracias a las notas aromáticas, esencias alquímicas, arquetípicas y chamánicas y al poder de la fitoterapia. Vestir tu hogar y tus espacios de emociones que te embriaguen, te ayudan a disfrutar de un placentario bienestar.",
    precio: 28.45,
    imagen: "Archivos/imagenes/Productos/producto32.png",
    categoria: "Abundancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 33,
    nombre: "Sérum Facial Corrector Despigmentante",
    referencia: "VP-033",
    descripcion: "Compuesto corrector y despigmentante que promueve el desvanecimiento de manchas de la edad y la hipermentación, nivelando el color de la piel y contribuyendo a la creación de un cutis más brillante y radiante.",
    precio: 65.05,
    imagen: "Archivos/imagenes/Productos/producto33.png",
    categoria: "Constancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 34,
    nombre: "Crema Facial Regenerativa Antimanchas FPS20",
    referencia: "VP-034",
    descripcion: "Protección mecánica mineral, sin Nanopartículas, que nos preserva, entre un 94-95%, de  las radiaciones UVA, UVB, IR y HEV. Para todo tipo de pieles, esta crema de tratamiento nutre, repara, unifica y reduce la hiperpigmentación.",
    precio: 56.50,
    imagen: "Archivos/imagenes/Productos/producto34.png",
    categoria: "Constancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 35,
    nombre: "Crema Facial Antimanchas Iluminadora",
    referencia: "VP-035",
    descripcion: "Mantiene el tono de la piel uniforme, minimizada los signos de la edad y los desequilibrios de pigmentación, característicos de pieles envejecidas. Ideal para una profunda regeneración, durante la noche.",
    precio: 68.80,
    imagen: "Archivos/imagenes/Productos/producto35.png",
    categoria: "Constancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 36,
    nombre: "Loción Capilar Bioestimulante",
    referencia: "VP-036",
    descripcion: "Loción capilar diseñada para combatir la caída del cabello y fortalecer desde la raíz a las puntas. Su fórmula avanzada actúa en sinergia para revitalizar el cuero cabelludo, estimular el crecimiento y reparar el cabello debilitado.",
    precio: 28.75,
    imagen: "Archivos/imagenes/Productos/producto36.png",
    categoria: "Constancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 37,
    nombre: "Elixir Corporal Reductor Drenante",
    referencia: "VP-037",
    descripcion: "Para todo tipo de pieles, este aceite corporal con acción lipolítica, reafirmante, drenante y tonificante, es ideal para quienes quieren obtener una doble acción: disolver los acúmulos de grasa localizada y reafirmar los tejidos.",
    precio: 57.80,
    imagen: "Archivos/imagenes/Productos/producto37.png",
    categoria: "Constancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 38,
    nombre: "Bálsamo Corporal Hidratante Regenerador",
    referencia: "VP-038",
    descripcion: "Bálsamo corporal Intensivo, con micropartículas que hidratan, nutren, calman y regeneran las pieles extremadamente secas y castigadas. Ideal para las zonas doloridas que requieren máxima atención y cuidado.",
    precio: 30.80,
    imagen: "Archivos/imagenes/Productos/producto38.png",
    categoria: "Constancia",
    stock: 40,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales",
  },
  {
    id: 39,
    nombre: "FREEDOM",
    referencia: "PC-01",
    descripcion: "El manejo del dolor es un factor clave para un estilo de vida saludable. Menos dolor conduce a una mayor movilidad y energía. Freedom Patch proporciona alivio sobre los síntomas de dolores de músculos y articulaciones asociados con el ejercicio, las tareas del hogar y las actividades diarias.",
    indicado: [
      "Dolores",
      "Molestias musculares",
      "Molestias Articulares"
    ],
    beneficios: [
      "Alivio inmediato del dolor",
      "Alivio durante 24 horas",
      "No produce somnolencia",
      "Aplicar en la zona de mayor dolor o en la 7ª vértebra cervical",
      "Ideal en conbinación con Liberty"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches1.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "PLazo de 1-3 días laborales",
  },
  {
    id: 40,
    nombre: "LIBERTY",
    referencia: "PC-02",
    descripcion: "Mejorar la forma en que nos movemos y la estabilidad corporal, son pilares para un estilo de vida saludable y óptima actividad diaria. Liberty Patch es una tecnología que puede ayudar en un mejor equilibrio y estabilidad. Este parche se puede utilizar para potenciar la acción de otro Super Patch, aplicándolos simultáneamente.",
    indicado: [
      "Equilibrio",
      "Estabilidad",
      "Más Energia"
    ],
    beneficios: [
      "Aumenta los efectos de otros parches",
      "Más energia",
      "Más fuerza",
      "Más equilibrio y estabilidad",
      "Recuperación más rapida",
      "Reducción de la inflamación",
      "Mejor amplitud de movimiento",
      "Mayor homeostasis neurológica"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches2.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "PLazo de 1-3 días laborales",
  },
  {
    id: 41,
    nombre: "REM",
    referencia: "PC-03",
    descripcion: "Un sueño reparador ayuda al rejuvenecimiento de la mente y el cuerpo y es un factor clave para un estilo de vida saludable. REM Patch puede favorecer un ciclo de sueño equilibrado, lo que facilita la salud general.",
    indicado: [
      "La Mejora del Sueño"
    ],
    beneficios: [
      "Dormir Mejor",
      "Todos los parches de dormir mejor: favorecen la recuperación del cuerpo y la mente",
      "Utilizar cuando la producción de melatonia se reduce significativamente"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches3.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 42,
    nombre: "VICTORY",
    referencia: "PC-04",
    descripcion: "La fuerza, la potencia, el equilibrio, la agilidad y la recuperación son los pilares para alcanzar los niveles más altos de rendimiento deportivo y también para mantener una vida activa y saludable. Victory Pach puede potenciar el bienestar general al mejorar la energía de los usuarios, el sentido del equilibrio y la resistencia.",
    indicado: [
      "Energía",
      "Equilibrio",
      "Bienestar General",
      "Rendimiento Deportivo",
      "Fuerza",
      "Resistencia",
      "Estabilidad"
    ],
    beneficios: [
      "Mejora las actividades atléticas",
      "Mejor Rendimiento",
      "Más energía y más fuerza",
      "Mayor equlibrio, estabilidad",
      "Mayor agilidad",
      "Mayor vigor resistencia",
      "Recuperación mas rápida",
      "Mejora de la neurofunción",
      "Mejora de la VFC",
      "Mejora la amplitud de movimiento",
      "Mayor alivio de la neuropatia"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches4.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "PLazo de 1-3 días laborales"
  },
  {
    id: 43,
    nombre: "PEACE",
    referencia: "PC-05",
    descripcion: "El estrés es un enemigo para nuestra calidad de vida. Tratar con él nunca ha sido más fácil. El Peace Patch puede mejorar el bienestar general a través de la estimulación vibrotáctil, que permite a los usuarios experimentar naturalmente una mayor claridad y calma.",
    indicado: [
      "Estrés",
      "Bienestar General",
      "Claridad",
      "Calma"
    ],
    beneficios: [
      "Controlar y reducir estrés",
      "Calma inmediatamente",
      "Dormir mejor"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches5.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborales"
  },
  {
    id: 44,
    nombre: "DEFEND",
    referencia: "PC-06",
    descripcion: "Un sistema inmunológico saludable es clave para el bienestar general. Defend Patch es una tecnología no invasiva y libre de fármacos que fortalece la inmunidad mediante estimulación vibrotáctil, facilitando así una salud óptima.",
    indicado: [
      "Respaldo del sitema inmunitario",
      "Mayor Bienestar",
      "Protección"
    ],
    beneficios: [
      "Mayor apoyo al sistema inmunológico",
      "Mejora del Flujo Sanguineo",
      "Regeneración y recuperación mas rápida",
      "Mejora del proceso natural de recuperación",
      "Ayuda a controlar las alergias y la congestión nasal"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches6.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 45,
    nombre: "IGNITE",
    referencia: "PC-07",
    descripcion: "Mantener equilibradas las calorías ingeridas y las calorías quemadas, son factores clave para conseguir un peso saludable. Ignite Patch ayuda a respaldar el consumo de energía, optimizando la tasa metabólica en reposo. La “tasa metabólica en reposo”, es la cantidad de calorías quemadas en estados de inactividad.",
    indicado: [
      "Regular el metabolismo",
      "Consumo de Energia",
      "Optimiza tasa metabóica en reposo"
    ],
    beneficios: [
      "Aumento de un 25% de la tasa matabólica en reposo",
      "Quema más calorias",
      "Disminución del apetito",
      "Mejora de la función intestinal",
      "Necesidad de aplicación a largo plazo"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches7.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 46,
    nombre: "FOCUS",
    referencia: "PC-08",
    descripcion: "La concentración es clave para aprender, competir y crear. Las distracciones y los desafíos pueden disminuir nuestro rendimiento y alejarnos de nuestros objetivos. Focus Patch puede mejorar el bienestar general a través de la estimulación vibrotáctil, lo que permite a los usuarios experimentar naturalmente un mejor enfoque y claridad.",
    indicado: [
      "Enfoque Mental",
      "Concentración",
      "Claridad"
    ],
    beneficios: [
      "Aumento de la concentración",
      "Mejora de la atención y la claridad",
      "Mejora las capacidades de aprendizaje, creación, toma de decisiones, etc",
      "Mejora la función cognitiva del cerebro"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches8.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 47,
    nombre: "JOY",
    referencia: "PC-09",
    descripcion: "El optimismo y la felicidad son quizás dos de los aspectos más importantes del espíritu humano. Joy Patch puede mejorar el sentido de bienestar y felicidad a través de la estimulación vibrotáctil. Lo que permite a los usuarios sentirse naturalmente lo mejor posible.",
    indicado: [
      "Mejorar la sensación de bienestar y felecidad"
    ],
    beneficios: [
      "Sentimiento Natural de alegría",
      "Actitud positiva",
      "Sensación de felicidad y optimismo"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches9.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 48,
    nombre: "KICK IT",
    referencia: "PC-010",
    descripcion: "Los malos hábitos pueden robar la calidad de vida. Estos hábitos suelen estar anclados en una compleja red de intenciones, pensamientos y acciones repetidas. Kick It Patch es una solución revolucionaria sin drogas para recuperar el control de nuestras vidas y hábitos.",
    indicado: [
      "Ayudar a recuperar el control",
      "Mejores Hábitos"
    ],
    beneficios: [
      "Ayuda a mejorar los malos habitos que pueden robar la calidad de vida de una persona",
      "Lucha contra los antojos",
      "Una solución revolucionaria para controlar los malos hábitos sin drogas",
      "Debe aplicarse a largo plazo"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches10.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 49,
    nombre: "ROCKET",
    referencia: "PC-011",
    descripcion: "Optimizar el rendimiento y alcanzar un estado de realización son piedras angulares del bienestar. Rocket Patch es una solución que, al incorporarse a una rutina saludable, tiene el potencial de aumentar el rendimiento y mejorar la satisfacción del bienestar general.",
    indicado: [
      "Aumentar el rendimiento",
      "Mejorar la satisfacción"
    ],
    beneficios: [
      "Aumenta la producción de testosterona",
      "Rstauración de la energía",
      "Mejora la resistencia",
      "Más pasión",
      "En mujeres ayuda al proceso de la menopausia"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches11.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 50,
    nombre: "LUMI",
    referencia: "PC-012",
    descripcion: "Lumi Patch es una tecnología que puede ayudar en su rutina de cuidado de la piel, cuando se combina con una dieta equilibrada, ejercicio regular e hidratación y descanso adecuado. Abraza el camino hacia una tez radiante y un enfoque holístico para el cuidado y el bienestar de la piel.",
    indicado: [
      "Cuidado de la piel",
      "Tez radiante"
    ],
    beneficios: [
      "Piel luminosa y radiante",
      "Activasión biofotónica natural",
      "Alivia irritaciones de la piel",
      "Ayuda con procesos alérgicos y algunas enfermedades de la piel"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches12.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 51,
    nombre: "BOOST",
    referencia: "PC-013",
    descripcion: "El Boost Super Patch es tu aliado para mantenerte activo y enfocado en cualquier momento. Ofrece energía sostenida sin caídas ni efectos secundarios. Ideal para atletas, profesionales, estudiantes y aventureros.",
    indicado: [
      "Energía natural",
      "Sin nerviosismo ni bajones"
    ],
    beneficios: [
      "Sin cafeína",
      "Sin azúcar"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches13.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 52,
    nombre: "ZEN",
    referencia: "pc-014",
    descripcion: "La creatividad y la claridad florecen cuando la mente está abierta y equilibrada",
    beneficios: [
      "Optimiza el desempeño mental manteniendo equilibrio emocional"
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches14.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  },
  {
    id: 53,
    nombre: "ASSURE",
    referencia: "pc-015",
    descripcion: "Apoyo en equilibrio fisico y sensación de estabilidad",
    indicado: [
      "Sensación de mareos en el coche, barco, avión, etc."
    ],
    precio: 80.00,
    imagen: "Archivos/imagenes/Parches/parches15.png",
    categoria: "Parches",
    stock: 49,
    envio: "Envío gratis apartir de 50 €",
    plazo: "Plazo de 1-3 días laborables"
  }
];